[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Triggering new deployment to run migrations
[deploy.env]
PYTHONUNBUFFERED = "1"
DJANGO_SETTINGS_MODULE = "news.settings"
PORT = "8000" 