# Generated by Django 4.0.1 on 2022-02-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspost",
            name="likes",
            field=models.IntegerField(default=0, verbose_name="кількість лайків"),
        ),
    ]
