# Generated by Django 4.0.1 on 2022-02-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsApp", "0002_newspost_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspost",
            name="description",
            field=models.CharField(default="", max_length=1024, verbose_name="Опис"),
        ),
    ]
