# Generated by Django 4.0.1 on 2022-02-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_newspost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='description',
            field=models.TextField(default='', max_length=1024, verbose_name='Опис'),
        ),
    ]
