# Generated by Django 4.0.1 on 2022-04-02 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("newsApp", "0009_remove_like_post_remove_like_reporter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="newsApp.newspost",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="reporter",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.RemoveField(
            model_name="newspost",
            name="likes",
        ),
        migrations.AddField(
            model_name="newspost",
            name="likes",
            field=models.IntegerField(default=0, verbose_name="Кількість лайків"),
        ),
        migrations.AlterField(
            model_name="newspost",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="post_views", to="newsApp.Ip"
            ),
        ),
    ]
