# Generated by Django 4.0.1 on 2022-04-27 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("newsApp", "0012_alter_newspost_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="time",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, verbose_name="Час"
            ),
            preserve_default=False,
        ),
    ]
